import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import * as ts from "typescript";
import { describe, expect, it } from "vitest";

import type { TsLibManifest } from "@/typecheck/libs";

// `pretest` runs scripts/sync-ts-libs.mjs, so this always describes a payload
// generated from the currently installed compiler.
const libDir = resolve(process.cwd(), "public", "ts-lib");
const manifest = JSON.parse(
  readFileSync(resolve(libDir, "manifest.json"), "utf8"),
) as TsLibManifest;

describe("ts-lib payload", () => {
  // The drift guard. Bumping `typescript` without regenerating the payload
  // would leave the browser checking against another compiler's standard
  // library — different globals, different diagnostics, and a lesson that
  // passes CI while lying to the learner.
  it("was generated by the installed compiler", () => {
    expect(manifest.typescriptVersion).toBe(ts.version);
  });

  it("is still exactly TypeScript 6.0.3", () => {
    // TypeScript 7 is a Go binary with no programmatic API and cannot run in a
    // browser. If this fails, the in-browser checker is gone, not just stale.
    expect(ts.version).toBe("6.0.3");
  });

  it("carries the baseline lib the host always requests", () => {
    expect(manifest.defaultLib).toBe("lib.es2022.d.ts");
    expect(manifest.entryLibs).toContain("es2022");
    expect(manifest.closures.es2022).toContain("lib.es2022.d.ts");
  });

  it("records every file it copied, byte length and digest", () => {
    const fileNames = Object.keys(manifest.files);
    expect(fileNames.length).toBeGreaterThan(50);

    for (const fileName of fileNames) {
      const path = resolve(libDir, fileName);
      expect(
        existsSync(path),
        `${fileName} is missing from public/ts-lib`,
      ).toBe(true);

      const bytes = readFileSync(path);
      const digest = `sha384-${createHash("sha384").update(bytes).digest("base64")}`;

      expect(bytes.byteLength).toBe(manifest.files[fileName].bytes);
      expect(digest).toBe(manifest.files[fileName].integrity);
    }
  });

  it("resolves each closure transitively, so the compiler never asks for a file we did not ship", () => {
    for (const [entryLib, closure] of Object.entries(manifest.closures)) {
      const inClosure = new Set(closure);

      for (const fileName of closure) {
        const text = readFileSync(resolve(libDir, fileName), "utf8");
        const references = ts
          .preProcessFile(text, false, false)
          .libReferenceDirectives.map(
            (reference) => `lib.${reference.fileName}.d.ts`,
          );

        for (const reference of references) {
          expect(
            inClosure.has(reference),
            `${entryLib}: ${fileName} references ${reference}, which the closure omits`,
          ).toBe(true);
        }
      }
    }
  });

  it("lists dependencies before the files that reference them", () => {
    const closure = manifest.closures.es2022;
    expect(closure.indexOf("lib.es5.d.ts")).toBeLessThan(
      closure.indexOf("lib.es2015.d.ts"),
    );
    expect(closure.indexOf("lib.es2015.d.ts")).toBeLessThan(
      closure.indexOf("lib.es2022.d.ts"),
    );
  });

  it("keeps the DOM out of the baseline", () => {
    expect(manifest.closures.es2022).not.toContain("lib.dom.d.ts");
    expect(manifest.closures.dom).toContain("lib.dom.d.ts");
  });

  it("is byte-for-byte reproducible", () => {
    // Re-running the generator must produce no diff, or `prebuild` would
    // rewrite the payload on every build and defeat HTTP caching.
    expect(() =>
      execFileSync(process.execPath, ["scripts/sync-ts-libs.mjs", "--check"], {
        cwd: process.cwd(),
      }),
    ).not.toThrow();
  });
});
