/**
 * Lazy, cached, same-origin delivery of the TypeScript standard library.
 *
 * The `lib.*.d.ts` files come out of our own `public/ts-lib/`, generated by
 * `scripts/sync-ts-libs.mjs` — never a CDN, so the deployed
 * `connect-src 'self'` holds and nobody else gets to decide what the compiler
 * reads. Nothing is fetched until a check actually needs it: the 459 KB ES2022
 * baseline is paid on the first keystroke, and the DOM's further 2.1 MB only if
 * a lesson asks for it.
 *
 * Every file is checked against the SHA-384 digest recorded at build time
 * wherever the platform exposes SubtleCrypto.
 */

/** Written by `scripts/sync-ts-libs.mjs` next to the files it describes. */
export interface TsLibManifest {
  /** The compiler these files were copied from. The drift test pins it. */
  typescriptVersion: string;
  defaultLib: string;
  entryLibs: string[];
  /** Entry lib name -> its transitive closure, dependencies first. */
  closures: Record<string, string[]>;
  files: Record<string, { bytes: number; integrity: string }>;
}

export const TS_LIB_DIRECTORY = "ts-lib";
export const TS_LIB_MANIFEST = "manifest.json";

/**
 * Public assets live under the site's base path, which is configurable so the
 * site can be hosted from a sub-path. Resolving against the current location
 * matters inside a worker, whose own URL is somewhere under `/assets/`.
 */
export function tsLibUrl(fileName: string): string {
  const base = import.meta.env?.BASE_URL ?? "/";
  const path = `${base.endsWith("/") ? base : `${base}/`}${TS_LIB_DIRECTORY}/${fileName}`;
  return typeof location === "undefined"
    ? path
    : new URL(path, location.href).toString();
}

function toBase64(buffer: ArrayBuffer): string {
  let binary = "";
  for (const byte of new Uint8Array(buffer))
    binary += String.fromCharCode(byte);
  return btoa(binary);
}

async function assertIntegrity(
  fileName: string,
  bytes: ArrayBuffer,
  expected: { bytes: number; integrity: string },
): Promise<void> {
  if (bytes.byteLength !== expected.bytes) {
    throw new Error(
      `${fileName} is ${bytes.byteLength} bytes, manifest says ${expected.bytes}`,
    );
  }

  // Absent on a non-secure origin (a plain-http LAN preview, say). The
  // same-origin fetch is the primary control; skipping the digest there is
  // better than refusing to run locally.
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) return;

  const actual = `sha384-${toBase64(await subtle.digest("SHA-384", bytes))}`;
  if (actual !== expected.integrity) {
    throw new Error(
      `${fileName} does not match its recorded digest — refusing to type-check against it`,
    );
  }
}

export interface LibLoader {
  /** Live view of what has been loaded; the compiler host reads it directly. */
  readonly files: ReadonlyMap<string, string>;
  /** Loads the closure of every named entry lib. Idempotent and cached. */
  ensure(entryLibs: string[]): Promise<void>;
  manifest(): Promise<TsLibManifest>;
}

export interface LibLoaderOptions {
  /** Test seam. Defaults to `globalThis.fetch`. */
  fetchResource?: (url: string) => Promise<Response>;
}

export function createLibLoader(options: LibLoaderOptions = {}): LibLoader {
  const fetchResource =
    options.fetchResource ??
    ((url: string) => fetch(url, { cache: "force-cache" }));

  const files = new Map<string, string>();
  const inFlight = new Map<string, Promise<void>>();
  let manifestPromise: Promise<TsLibManifest> | undefined;

  async function loadManifest(): Promise<TsLibManifest> {
    const response = await fetchResource(tsLibUrl(TS_LIB_MANIFEST));
    if (!response.ok) {
      throw new Error(
        `cannot load the standard-library manifest (${response.status}); run \`pnpm run sync:ts-libs\``,
      );
    }
    return (await response.json()) as TsLibManifest;
  }

  async function loadFile(
    fileName: string,
    manifest: TsLibManifest,
  ): Promise<void> {
    const expected = manifest.files[fileName];
    if (!expected) throw new Error(`${fileName} is not in the manifest`);

    const response = await fetchResource(tsLibUrl(fileName));
    if (!response.ok) {
      throw new Error(`cannot load ${fileName} (${response.status})`);
    }

    const bytes = await response.arrayBuffer();
    await assertIntegrity(fileName, bytes, expected);
    files.set(fileName, new TextDecoder().decode(bytes));
  }

  return {
    files,

    manifest() {
      manifestPromise ??= loadManifest();
      return manifestPromise;
    },

    async ensure(entryLibs) {
      const manifest = await this.manifest();

      const needed = new Set<string>();
      for (const entryLib of entryLibs) {
        const closure = manifest.closures[entryLib];
        if (!closure) {
          throw new Error(
            `the standard-library payload carries no lib "${entryLib}" ` +
              `(it has: ${manifest.entryLibs.join(", ")}). ` +
              `Add it to ENTRY_LIBS in scripts/sync-ts-libs.mjs.`,
          );
        }
        for (const fileName of closure) {
          if (!files.has(fileName)) needed.add(fileName);
        }
      }
      await Promise.all(
        [...needed].map((fileName) => {
          let pending = inFlight.get(fileName);
          if (!pending) {
            pending = loadFile(fileName, manifest).finally(() => {
              inFlight.delete(fileName);
            });
            inFlight.set(fileName, pending);
          }
          return pending;
        }),
      );
    },
  };
}
